---
# Source: flux/charts/flux2/templates/kustomize-controller-sa.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: kustomize-controller
    app.kubernetes.io/instance: "flux"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/version: "2.5.1"
    app.kubernetes.io/part-of: flux
    helm.sh/chart: flux2-2.15.0
  name: kustomize-controller
