apiVersion: "cilium.io/v2"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "test-pool"
spec:
  blocks:
  - start: "192.168.1.40"
    stop: "192.168.1.40"
---
apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: test-policy
spec:
  interfaces:
  - enp4s0
  externalIPs: false
  loadBalancerIPs: true
