apiVersion: v2
name: flux
description: wrapper over flux2
type: application
version: 2.17.2
dependencies:
- name: flux2
  version: '*'
  repository: https://fluxcd-community.github.io/helm-charts
  condition: flux2.enabled
