---
# Source: forgejo/templates/gitea/ssh-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: forgejo-ssh
  namespace: "forgejo"
  labels:
    helm.sh/chart: forgejo-16.0.2
    app: forgejo
    app.kubernetes.io/name: forgejo
    app.kubernetes.io/instance: forgejo
    app.kubernetes.io/version: "14.0.2"
    version: "14.0.2"
    app.kubernetes.io/managed-by: Helm
  annotations:
    metallb.universe.tf/allow-shared-ip: test
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
  - name: ssh
    port: 9022
    targetPort: ssh
    protocol: TCP
    nodePort: 32222
  selector:
    app.kubernetes.io/name: forgejo
    app.kubernetes.io/instance: forgejo
