apiVersion: v2
name: renovate
description: wrapper over renovate
type: application
version: 46.3.1
dependencies:
- name: renovate
  version: '*'
  repository: https://docs.renovatebot.com/helm-charts
