---
# Cronjob instance for clux
renovate:
  repositories: ['"clux/renovate", "clux/muslrust"']
  fullnameOverride: 'renovate-clux'
  envFrom:
  # Classic PAT https://docs.renovatebot.com/modules/platform/github/#authentication
  # For clux's repos via sszynrae. Have to sszynrae as collaborator to the repos.
  # Update classic pat on expiry and update the renovate-pat-sszynrae-classic secret.
  - secretRef:
      name: renovate-ssz-pat-classic
